[pytest]
markers = 
    launch: To Launch the Chrome
    ui_valid: UI More Valdation
    network_validation: OTP Validation




;addopts = --headed --slowmo=100 --browser chromium
;addopts = --headed --slowmo=50 --browser-channel chrome
